### ISSUE TITLE
Error While Exporting as a .osz

### ISSUE THREAD

**Issue by TEKBot101** [Corne2Plum3/fnf2osumania#12]
Traceback (most recent call last):
  File "fnf_converter.py", line 529, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The specified file can not be found

**Comment by Corne2Plum3** [comment]
You probably don't have ffmpeg installed on your computer. (duplicate of #5 btw)
