### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Alt Idle Animation'

### ISSUE THREAD

**Issue by dothenotive** [Corne2Plum3/fnf2osumania#20]
Converter stops at 70% and throws an error

```
Traceback (most recent call last):
  File "fnf_converter.py", line 551, in exportAsOsz
  File "fnf_converter.py", line 176, in exportOsuFile
  File "fnf_converter.py", line 272, in getNotesAll8K
  File "fnf_converter.py", line 303, in getNotesPlayer
ValueError: invalid literal for int() with base 10: 'Alt Idle Animation'
```
![Screenshot_1665](https://user-images.githubusercontent.com/69473285/152689333-b001bc03-8707-4753-817c-9f7e39ec87c6.png)

FFmpeg is installed, and the python version is 3.9

**Comment by dothenotive** [comment]
Issue closed; chart-specific issue.
In my case, there is a `string` inside of an number-only array.
![image](https://user-images.githubusercontent.com/69473285/152689814-28e30dd7-eaaf-4693-a073-f6a03c7f1367.png)


First way on how to fix it:
1) Delete the text and you should be good.
![image](https://user-images.githubusercontent.com/69473285/152689779-2eb7b39b-2466-4044-8713-f5a4eb300174.png)

Also, it *may* raise some errors; instead of deleting only the text, delete the whole note itself
Second way on how to fix it:

2) Delete the note.
![image](https://user-images.githubusercontent.com/69473285/152689747-f105434e-6e8e-478b-8eae-5ff162995587.png)
