### ISSUE TITLE
Error window displayed for SystemExit exceptions

### ISSUE THREAD

**Issue by Corne2Plum3** [Corne2Plum3/fnf2osumania#4]
**Describe the bug**
When you press cancel while exporting, an error window spawns to show an SystemExit exception.

It shouldn't be visible because it may be confuse for some users.
```
Traceback (most recent call last):
  File "d:\Corne2Plum3\osu! related\fnf2osumania\fnf_converter.py", line 505, in exportAsOsz
    ogg_1 = AudioSegment.from_file(osu_map.audio1_path, format="ogg")  # create AudioSegment object from pydub library
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydub\audio_segment.py", line 718, in from_file
    p_out, p_err = p.communicate(input=stdin_data)
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1296, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 1061, in _wait_for_tstate_lock
    lock.release()
  File "C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 1061, in _wait_for_tstate_lock
    lock.release()
  File "d:\Corne2Plum3\osu! related\fnf2osumania\thread_with_trace.py", line 42, in localtrace
    raise SystemExit()
SystemExit
```
(replaced my username by %USERNAME% btw)

**Error message**
If you got an error message, post it here.

**OS and version:**
Windows 10
Version 1.1 using the source code

**Used files:**
Not needed.

**Comment by Corne2Plum3** [comment]
Fixed with v1.1.5 release
