### ISSUE TITLE
When a note has more than 3 arguments, the program crashes.

### ISSUE THREAD

**Issue by windows10win7posreadywoeskio** [Corne2Plum3/fnf2osumania#7]
**Describe the bug**
Describe what happened.
When i was waiting for it to convert, when it got to 42%... It crashed.

**Error message**
If you got an error message, post it here.
Traceback (most recent call last):
  File "fnf_converter.py", line 528, in exportAsOsz
  File "fnf_converter.py", line 153, in exportOsuFile
  File "fnf_converter.py", line 249, in getBPMList
  File "fnf_converter.py", line 269, in getNotesAll8K
  File "fnf_converter.py", line 306, in getNotesPlayer
TypeError: '<' not supported between instances of 'str' and 'int'

**Screenshots**
(this screenshot was taken recently)
![image](https://user-images.githubusercontent.com/56192384/138577916-1e69e6cb-60e6-4ef7-b4be-4c0ff840f205.png)

**OS and version:**
Tell us on what you ran the program (Window, Linux, ...) and which version you used.
Windows 10 Insider Preview Pro 21h1
Python version: 3.10
(oh wait i get what version means now) 1.1.1 (latest)

**Used files:**
If you input files in this program, post them here (just drag the files in this box), it would be useful to understand how the bug happened.
they're here since i can't really attach jsons
[screwed.zip](https://github.com/Corne2Plum3/fnf2osumania/files/7403963/screwed.zip)

**Additional context**
Something to add?
no

**Comment by Corne2Plum3** [comment]
Found in v1.2.0
